apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" #This should start first before any configs to prevent config like ip address pool deployed before main metallb deployed
spec:
  project: default

  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.16.1

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true