apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # infrastructure/metallb/config will not start if no change in parent application
spec:
  project: default

  source:
    repoURL: git@github.com:tobing/kubernetes-gitops.git
    targetRevision: HEAD
    path: infrastructure/metallb/config

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
